# We do not automatically build the recording agent, which requires SDL. To build it, run
#
# > make recordingAgent
all: alewrap

alewrap: 
	make -f Makefile.alewrap

clean:
	make -f Makefile.alewrap clean

