USE_SDL := 1

# This will likely need to be changed to suit your installation.
ALE := ../..

FLAGS := -I$(ALE)/src -I$(ALE)/src/controllers -I$(ALE)/src/os_dependent -I$(ALE)/src/environment -I$(ALE)/src/external -L$(ALE)
CXX := g++ -shared -fPIC
FILE := alewrap
LDFLAGS := -std=c++11 -lale -lz

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
    FLAGS += -Wl,-rpath=$(ALE)
endif
ifeq ($(UNAME_S),Darwin)
    FLAGS += -framework Cocoa
endif

ifeq ($(strip $(USE_SDL)), 1)
  DEFINES += -D__USE_SDL -DSOUND_SUPPORT
  FLAGS += $(shell sdl-config --cflags)
  LDFLAGS += $(shell sdl-config --libs)
endif

all: alewrap

alewrap:
	$(CXX) $(DEFINES) $(FLAGS) $(FILE).cc $(LDFLAGS) -o lib$(FILE).so

clean:
	rm -rf alewrap *.o
